cards = "div.wf-card"
header = "a.wf-module-header"
stream = "a.wf-module-item.module-item"
stream_name = "span.module-item-title-sub"
stream_viewer_count = "span.stream-item-count"
flag = "i.module-item-flag"
