matches-upcoming = "div.js-home-matches-upcoming"
matches-completed = "div.js-home-matches-completed"
header = "a.wf-label.mod-sidebar"
match = "a.wf-module-item.mod-match"
live = "div.h-match-eta.mod-live"
event_name = "div.h-match-preview-event"
event_series = "div.h-match-preview-series"
teams = "div.h-match-team"
team_name = "div.h-match-team-name"
team_score = "div.h-match-team-score.mod-count"
match_scheduled_time = "div.h-match-preview-time"
